// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-vue3-admin-server/app/model/internal"
)

// Relation is the golang structure for table admin_relation.
type Relation internal.Relation

// Fill with you ideas below.
