// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-react-admin-server/app/model/internal"
)

// RoleResource is the golang structure for table admin_role_resource.
type RoleResource internal.RoleResource

// Fill with you ideas below.
