// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-vue3-admin-server/app/model/internal"
)

// Role is the golang structure for table admin_role.
type Role internal.Role

// Fill with you ideas below.

// CreateRoleReq 用于接受创建角色请求
type CreateRoleReq struct {
	ParentId string `json:"parentId"` // 父角色id
	RoleName string `json:"roleName"` // 角色名称
	Alias    string `json:"alias"`    // 角色别名
}
