// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-vue3-admin-server/app/model/internal"
)

// User is the golang structure for table admin_user.
type User internal.User

// Fill with you ideas below.
