// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Relation is the golang structure for table admin_relation.
type Relation struct {
	Id        int64       `orm:"id,primary" json:"id"`        //
	UserId    string      `orm:"user_id"    json:"userId"`    // 用户id
	RoleId    string      `orm:"role_id"    json:"roleId"`    // 角色id
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` // 创建时间
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` // 更新时间
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` // 删除时间
}
