// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// RoleResource is the golang structure for table admin_role_resource.
type RoleResource struct {
	Id         int64       `orm:"id,primary"  json:"id"`         //
	RoleId     string      `orm:"role_id"     json:"roleId"`     // 角色id
	ResourceId string      `orm:"resource_id" json:"resourceId"` // 资源id
	CreateBy   int64       `orm:"create_by"   json:"createBy"`   // 创建人
	CreatedAt  *gtime.Time `orm:"created_at"  json:"createdAt"`  // 创建时间
	UpdatedBy  int64       `orm:"updated_by"  json:"updatedBy"`  // 更新人
	UpdatedAt  *gtime.Time `orm:"updated_at"  json:"updatedAt"`  // 更新时间
	DeleteBy   int64       `orm:"delete_by"   json:"deleteBy"`   // 删除人
	DeletedAt  *gtime.Time `orm:"deleted_at"  json:"deletedAt"`  // 删除时间时间
}
