// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-vue3-admin-server/app/dao/internal"
)

// relationDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type relationDao struct {
	*internal.RelationDao
}

var (
	// Relation is globally public accessible object for table admin_relation operations.
	Relation = &relationDao{
		internal.Relation,
	}
)

// Fill with you ideas below.
