// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-vue3-admin-server/app/dao/internal"
	"gf-vue3-admin-server/app/model"
)

// resourceDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type resourceDao struct {
	*internal.ResourceDao
}

var (
	// Resource is globally public accessible object for table admin_resource operations.
	Resource = &resourceDao{
		internal.Resource,
	}
)

// Fill with you ideas below.

// FindByNameAndType find resource by name and type
func (r *resourceDao) FindByNameAndType(name, types string) (resource *model.Resource, err error) {
	if len(name) <= 0 || len(types) <= 0 {
		return nil, nil
	}

	err = r.Where(r.Columns.Name, name).And(r.Columns.Type, types).Scan(&resource)
	return
}
