// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-react-admin-server/app/dao/internal"
)

// roleResourceDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type roleResourceDao struct {
	*internal.RoleResourceDao
}

var (
	// RoleResource is globally public accessible object for table admin_role_resource operations.
	RoleResource = &roleResourceDao{
		internal.RoleResource,
	}
)

// Fill with you ideas below.
